use [AcademyDB]

------------------------------------------------------------------ TEACHERS TABLE FAKE DATA ------------------------------------------------------------------

insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('10/21/2019', 0, 0, 'Scottie', 'Librarian', 703, 5847, 'Johncey');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('2/7/2008', 0, 0, 'Montague', 'Web Developer I', 813, 3474, 'Hanrott');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('1/26/1992', 0, 1, 'Ximenes', 'Tax Accountant', 1031, 1357, 'Antyshev');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('2/14/2015', 1, 0, 'Tedd', 'Clinical Specialist', 2260, 2638, 'Marriage');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('4/16/2011', 1, 0, 'Flem', 'Electrical Engineer', 872, 3663, 'Mithon');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('2/6/2015', 1, 1, 'Reagan', 'General Manager', 883, 2527, 'Dunkerley');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('2/25/2000', 1, 0, 'Zacharie', 'Cost Accountant', 1553, 1032, 'Reggio');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('6/5/2017', 0, 1, 'Gar', 'Health Coach I', 455, 2797, 'Iaduccelli');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('8/28/2011', 0, 1, 'York', 'Account Coordinator', 1254, 7428, 'Izon');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('3/4/2004', 0, 0, 'Arel', 'Human Resources Assistant I', 2522, 1124, 'Kellar');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('10/1/2003', 1, 0, 'Warren', 'Information Systems Manager', 1336, 2117, 'Nairns');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('2/18/2009', 0, 1, 'Clayson', 'Media Manager II', 780, 3569, 'Townes');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('8/23/2011', 1, 0, 'Meryl', 'Business Systems Development Analyst', 1154, 8609, 'Sizey');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('9/22/2012', 0, 1, 'Jethro', 'Payment Adjustment Coordinator', 491, 7722, 'Smidmor');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('5/12/2010', 1, 1, 'Randolf', 'Clinical Specialist', 886, 456, 'Cardero');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('5/14/2009', 1, 1, 'Leeland', 'Food Chemist', 1672, 8477, 'Pettingill');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('10/21/2010', 1, 1, 'Mattheus', 'Accounting Assistant I', 1906, 7279, 'Yates');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('6/26/2012', 0, 0, 'Taddeo', 'Administrative Assistant III', 1210, 2594, 'Yankishin');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('5/13/2000', 0, 0, 'Frederick', 'Quality Engineer', 2141, 9589, 'Pee');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('8/11/2016', 0, 0, 'Keene', 'General Manager', 2173, 9504, 'Ramelet');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('12/26/2017', 0, 0, 'Jozef', 'Business Systems Development Analyst', 1346, 3058, 'Clissell');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('9/6/2000', 0, 1, 'Jae', 'Geological Engineer', 1192, 8601, 'Crissil');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('8/3/2007', 0, 0, 'Dickie', 'Accountant II', 1575, 1116, 'Whittingham');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('2/19/2004', 1, 1, 'Ferrell', 'Marketing Manager', 71, 1278, 'Trout');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('1/3/2001', 1, 0, 'Ring', 'Mechanical Systems Engineer', 2876, 6975, 'Millhill');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('8/22/2018', 0, 0, 'Mose', 'Electrical Engineer', 559, 781, 'Loomis');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('2/26/2007', 1, 1, 'Briggs', 'VP Accounting', 138, 8128, 'Milley');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('8/13/1994', 0, 1, 'Morly', 'Staff Accountant IV', 1717, 7520, 'Gibling');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('7/29/2017', 0, 1, 'Kristos', 'Librarian', 262, 5749, 'Brookhouse');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('8/17/2022', 0, 1, 'Bjorn', 'Structural Analysis Engineer', 1378, 548, 'Tuminini');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('11/14/2022', 0, 1, 'Chic', 'Structural Engineer', 2173, 4972, 'Chaffyn');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('7/25/2015', 0, 1, 'Othello', 'Structural Analysis Engineer', 2739, 7802, 'Bortoloni');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('10/6/1995', 1, 0, 'Tobin', 'Physical Therapy Assistant', 134, 8218, 'Hulson');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('6/13/2011', 1, 1, 'Dudley', 'Desktop Support Technician', 137, 3953, 'Krystek');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('9/5/2010', 0, 0, 'Ogdan', 'Teacher', 1355, 1017, 'Deans');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('4/13/2018', 1, 0, 'Budd', 'Administrative Officer', 979, 3173, 'Chater');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('1/4/2007', 0, 0, 'Webb', 'Executive Secretary', 1, 7298, 'Miskimmon');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('9/25/2019', 0, 1, 'Ive', 'Senior Sales Associate', 613, 2810, 'Shiels');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('6/15/1995', 0, 0, 'Bradney', 'VP Accounting', 1539, 2033, 'Gajownik');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('2/18/2005', 1, 0, 'Reggis', 'VP Marketing', 2180, 1768, 'Mannagh');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('1/5/2010', 1, 1, 'Paddy', 'Junior Executive', 595, 7872, 'Erangy');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('12/30/2007', 0, 1, 'Talbot', 'VP Sales', 2759, 6303, 'Cubbon');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('5/31/2005', 0, 1, 'Morton', 'Nuclear Power Engineer', 1694, 3450, 'Dearle');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('1/20/2003', 0, 1, 'Ermin', 'Software Test Engineer IV', 819, 9843, 'Wallsam');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('10/29/2005', 1, 1, 'Rolf', 'Environmental Tech', 380, 4331, 'Welbourn');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('12/26/2001', 0, 0, 'Harvey', 'Structural Analysis Engineer', 520, 3629, 'Celli');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('4/13/2006', 0, 1, 'Max', 'Payment Adjustment Coordinator', 1467, 8415, 'Stollenwerck');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('7/22/2014', 1, 1, 'Frederigo', 'Senior Quality Engineer', 1097, 3390, 'Diament');
insert into Teachers (EmploymentDate, IsAssistant, IsProfessor, Name, Position, Premium, Salary, Surname) values ('7/4/1995', 1, 1, 'Cary', 'Operator', 600, 5663, 'Mauditt');

------------------------------------------------------------------ GROUPS TABLE FAKE DATA ------------------------------------------------------------------

insert into Groups (Name, Rating, Year) values ('Myrlene', 1, 5);
insert into Groups (Name, Rating, Year) values ('Germain', 5, 1);
insert into Groups (Name, Rating, Year) values ('Matthew', 2, 3);
insert into Groups (Name, Rating, Year) values ('Delcine', 0, 4);
insert into Groups (Name, Rating, Year) values ('Penn', 0, 2);
insert into Groups (Name, Rating, Year) values ('Dawn', 4, 1);
insert into Groups (Name, Rating, Year) values ('Colas', 5, 1);
insert into Groups (Name, Rating, Year) values ('Gussy', 1, 1);
insert into Groups (Name, Rating, Year) values ('Ricoriki', 4, 2);
insert into Groups (Name, Rating, Year) values ('Gwendolyn', 4, 4);
insert into Groups (Name, Rating, Year) values ('Andrew', 0, 3);
insert into Groups (Name, Rating, Year) values ('Melissa', 4, 3);
insert into Groups (Name, Rating, Year) values ('Lawton', 0, 1);
insert into Groups (Name, Rating, Year) values ('Guthry', 2, 3);
insert into Groups (Name, Rating, Year) values ('Susanna', 4, 3);
insert into Groups (Name, Rating, Year) values ('Sampson', 1, 1);
insert into Groups (Name, Rating, Year) values ('Fernando', 1, 1);
insert into Groups (Name, Rating, Year) values ('Ruddie', 0, 2);
insert into Groups (Name, Rating, Year) values ('Tarra', 5, 3);
insert into Groups (Name, Rating, Year) values ('Anabelle', 1, 1);
insert into Groups (Name, Rating, Year) values ('Beverly', 2, 4);
insert into Groups (Name, Rating, Year) values ('Elisabeth', 0, 3);
insert into Groups (Name, Rating, Year) values ('Florentia', 5, 5);
insert into Groups (Name, Rating, Year) values ('Ricca', 3, 3);
insert into Groups (Name, Rating, Year) values ('Tana', 3, 2);
insert into Groups (Name, Rating, Year) values ('Caty', 3, 3);
insert into Groups (Name, Rating, Year) values ('Zedekiah', 2, 1);
insert into Groups (Name, Rating, Year) values ('Dorothea', 4, 1);
insert into Groups (Name, Rating, Year) values ('Baily', 0, 1);
insert into Groups (Name, Rating, Year) values ('Carmelita', 1, 4);
insert into Groups (Name, Rating, Year) values ('Shae', 0, 5);
insert into Groups (Name, Rating, Year) values ('Rogerio', 0, 2);
insert into Groups (Name, Rating, Year) values ('Mariana', 0, 4);
insert into Groups (Name, Rating, Year) values ('Nettle', 2, 3);
insert into Groups (Name, Rating, Year) values ('Yvor', 2, 3);
insert into Groups (Name, Rating, Year) values ('Vivien', 5, 3);
insert into Groups (Name, Rating, Year) values ('Clarance', 1, 2);
insert into Groups (Name, Rating, Year) values ('Krystyna', 3, 4);
insert into Groups (Name, Rating, Year) values ('Richy', 3, 1);
insert into Groups (Name, Rating, Year) values ('Sarena', 3, 2);
insert into Groups (Name, Rating, Year) values ('Fields', 1, 4);
insert into Groups (Name, Rating, Year) values ('Zebadiah', 2, 1);
insert into Groups (Name, Rating, Year) values ('Starlin', 4, 2);
insert into Groups (Name, Rating, Year) values ('Rob', 4, 2);
insert into Groups (Name, Rating, Year) values ('Tabitha', 0, 5);
insert into Groups (Name, Rating, Year) values ('Teodoor', 4, 1);
insert into Groups (Name, Rating, Year) values ('Lotte', 3, 3);
insert into Groups (Name, Rating, Year) values ('Amber', 1, 3);
insert into Groups (Name, Rating, Year) values ('Gill', 5, 3);
insert into Groups (Name, Rating, Year) values ('Berte', 4, 3);

------------------------------------------------------------------ GROUPS TABLE FAKE DATA ------------------------------------------------------------------

insert into Faculties (Dean, Name) values ('Ginni Ogdahl', 'Structural Engineer');
insert into Faculties (Dean, Name) values ('Aloysia Bellingham', 'Human Resources Assistant I');
insert into Faculties (Dean, Name) values ('Patrice Luca', 'Developer III');
insert into Faculties (Dean, Name) values ('Yoko Niblett', 'VP Accounting');
insert into Faculties (Dean, Name) values ('Virginia LLelweln', 'Registered Nurse');
insert into Faculties (Dean, Name) values ('Wait Tomisch', 'Actuary');
insert into Faculties (Dean, Name) values ('Shermie Burgot', 'Senior Developer');
insert into Faculties (Dean, Name) values ('Rianon Eisikovitsh', 'Geologist IV');
insert into Faculties (Dean, Name) values ('Garry Bowton', 'Automation Specialist II');
insert into Faculties (Dean, Name) values ('Devland Duignan', 'General Manager');
insert into Faculties (Dean, Name) values ('Jacinthe Haygreen', 'Community Outreach Specialist');
insert into Faculties (Dean, Name) values ('Zedekiah Eagling', 'Senior Editor');
insert into Faculties (Dean, Name) values ('Jeannie Rampling', 'VP Product Management');
insert into Faculties (Dean, Name) values ('Mathias Zaple', 'Health Coach III');
insert into Faculties (Dean, Name) values ('Meg Belderfield', 'Physical Therapy Assistant');
insert into Faculties (Dean, Name) values ('Free Charon', 'VP Product Management');
insert into Faculties (Dean, Name) values ('Guenevere Camellini', 'Human Resources Manager');
insert into Faculties (Dean, Name) values ('Wren MacInerney', 'Associate Professor');
insert into Faculties (Dean, Name) values ('Tomkin Kings', 'Operator');
insert into Faculties (Dean, Name) values ('Humphrey Mylechreest', 'Information Systems Manager');
insert into Faculties (Dean, Name) values ('Ariela Grimsdyke', 'Engineer III');
insert into Faculties (Dean, Name) values ('Donni Speaks', 'Teacher');
insert into Faculties (Dean, Name) values ('Vernor Ernke', 'VP Accounting');
insert into Faculties (Dean, Name) values ('Cal Simmens', 'Marketing Assistant');
insert into Faculties (Dean, Name) values ('Penni Choak', 'Structural Analysis Engineer');
insert into Faculties (Dean, Name) values ('Wandis Byard', 'Paralegal');
insert into Faculties (Dean, Name) values ('Meir Kinsella', 'Chief Design Engineer');
insert into Faculties (Dean, Name) values ('Moss Cannaway', 'Marketing Assistant');
insert into Faculties (Dean, Name) values ('Mariel Parmley', 'Automation Specialist IV');
insert into Faculties (Dean, Name) values ('Andrea Marton', 'Project Manager');
insert into Faculties (Dean, Name) values ('Dido Bourges', 'Analyst Programmer');
insert into Faculties (Dean, Name) values ('Margarethe Schulke', 'Chief Design Engineer');
insert into Faculties (Dean, Name) values ('Diannne Gauson', 'Research Nurse');
insert into Faculties (Dean, Name) values ('Madel Aronin', 'Account Executive');
insert into Faculties (Dean, Name) values ('Lawton Havock', 'Payment Adjustment Coordinator');
insert into Faculties (Dean, Name) values ('Taddeo Worswick', 'Account Representative I');
insert into Faculties (Dean, Name) values ('Grethel Glanert', 'VP Quality Control');
insert into Faculties (Dean, Name) values ('Vinny Lyptrit', 'Speech Pathologist');
insert into Faculties (Dean, Name) values ('Bell Oglethorpe', 'Web Developer I');
insert into Faculties (Dean, Name) values ('Filia Ower', 'Recruiter');
insert into Faculties (Dean, Name) values ('Henrietta Gothard', 'Budget/Accounting Analyst I');
insert into Faculties (Dean, Name) values ('Fredelia Frier', 'Professor');
insert into Faculties (Dean, Name) values ('Sigfrid Gofford', 'Executive Secretary');
insert into Faculties (Dean, Name) values ('Sydney Aulton', 'Systems Administrator IV');
insert into Faculties (Dean, Name) values ('Franny Paine', 'Statistician IV');
insert into Faculties (Dean, Name) values ('Natassia Brend', 'Administrative Assistant IV');
insert into Faculties (Dean, Name) values ('Lindsey Lippini', 'Financial Analyst');
insert into Faculties (Dean, Name) values ('Lavena Grece', 'Assistant Professor');
insert into Faculties (Dean, Name) values ('Abelard Letessier', 'Senior Cost Accountant');
insert into Faculties (Dean, Name) values ('Gaye Simoni', 'Sales Associate');

------------------------------------------------------------------ GROUPS TABLE FAKE DATA ------------------------------------------------------------------

insert into Departments (Financing, Name) values ('$1067.15', 'General Manager');
insert into Departments (Financing, Name) values ('$1881.62', 'Senior Developer');
insert into Departments (Financing, Name) values ('$3148.04', 'Dental Hygienist');
insert into Departments (Financing, Name) values ('$1438.84', 'Operator');
insert into Departments (Financing, Name) values ('$1972.99', 'Environmental Tech');
insert into Departments (Financing, Name) values ('$1577.18', 'Community Outreach Specialist');
insert into Departments (Financing, Name) values ('$2094.52', 'Civil Engineer');
insert into Departments (Financing, Name) values ('$3142.75', 'Nurse');
insert into Departments (Financing, Name) values ('$1830.70', 'Desktop Support Technician');
insert into Departments (Financing, Name) values ('$2209.16', 'Actuary');
insert into Departments (Financing, Name) values ('$2622.32', 'Budget/Accounting Analyst III');
insert into Departments (Financing, Name) values ('$2876.93', 'Geologist II');
insert into Departments (Financing, Name) values ('$1758.69', 'Research Assistant IV');
insert into Departments (Financing, Name) values ('$3014.27', 'Compensation Analyst');
insert into Departments (Financing, Name) values ('$3014.54', 'Marketing Assistant');
insert into Departments (Financing, Name) values ('$1018.50', 'Computer Systems Analyst IV');
insert into Departments (Financing, Name) values ('$1820.00', 'Nurse');
insert into Departments (Financing, Name) values ('$1769.96', 'Quality Control Specialist');
insert into Departments (Financing, Name) values ('$1544.77', 'Senior Quality Engineer');
insert into Departments (Financing, Name) values ('$1972.42', 'Editor');
insert into Departments (Financing, Name) values ('$1847.44', 'Project Manager');
insert into Departments (Financing, Name) values ('$2701.58', 'Actuary');
insert into Departments (Financing, Name) values ('$2362.71', 'Marketing Assistant');
insert into Departments (Financing, Name) values ('$1840.29', 'Engineer III');
insert into Departments (Financing, Name) values ('$1962.72', 'Compensation Analyst');
insert into Departments (Financing, Name) values ('$3377.83', 'Account Executive');
insert into Departments (Financing, Name) values ('$1961.67', 'Geologist II');
insert into Departments (Financing, Name) values ('$1126.79', 'Physical Therapy Assistant');
insert into Departments (Financing, Name) values ('$2053.09', 'Structural Analysis Engineer');
insert into Departments (Financing, Name) values ('$1967.41', 'Internal Auditor');
insert into Departments (Financing, Name) values ('$2428.58', 'VP Product Management');
insert into Departments (Financing, Name) values ('$2414.66', 'Help Desk Technician');
insert into Departments (Financing, Name) values ('$1480.63', 'Web Designer I');
insert into Departments (Financing, Name) values ('$3483.27', 'Operator');
insert into Departments (Financing, Name) values ('$2606.87', 'Environmental Specialist');
insert into Departments (Financing, Name) values ('$1004.68', 'Librarian');
insert into Departments (Financing, Name) values ('$1777.82', 'Research Assistant II');
insert into Departments (Financing, Name) values ('$2871.76', 'Product Engineer');
insert into Departments (Financing, Name) values ('$1923.46', 'Environmental Tech');
insert into Departments (Financing, Name) values ('$2505.90', 'Information Systems Manager');
insert into Departments (Financing, Name) values ('$3136.56', 'Internal Auditor');
insert into Departments (Financing, Name) values ('$2410.87', 'Electrical Engineer');
insert into Departments (Financing, Name) values ('$1961.46', 'Account Executive');
insert into Departments (Financing, Name) values ('$1246.69', 'Media Manager I');
insert into Departments (Financing, Name) values ('$1263.12', 'Editor');
insert into Departments (Financing, Name) values ('$1373.82', 'Web Designer I');
insert into Departments (Financing, Name) values ('$1465.99', 'Data Coordinator');
insert into Departments (Financing, Name) values ('$1935.06', 'Automation Specialist I');
insert into Departments (Financing, Name) values ('$1583.25', 'Business Systems Development Analyst');
insert into Departments (Financing, Name) values ('$1375.53', 'Financial Advisor');